# Generated by Django 5.0.6 on 2024-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='739745553', editable=False, max_length=9),
        ),
    ]
