# Generated by Django 5.0.6 on 2024-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_account_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='828468437', editable=False, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('TELLER', 'teller'), ('USER', 'user')], max_length=30),
        ),
    ]
