# Generated by Django 5.0.6 on 2024-06-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_account_account_no_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='989417121', editable=False, max_length=9),
        ),
    ]
