# Generated by Django 5.0.6 on 2024-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_alter_account_account_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='878758614', editable=False, max_length=9),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'account_no'), name='unique_user_account'),
        ),
    ]
