# Generated by Django 5.0.6 on 2024-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='495701825', editable=False, max_length=9, unique=True),
        ),
    ]
