# Generated by Django 5.0.6 on 2024-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_alter_account_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='154310997', editable=False, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/account_qr/'),
        ),
    ]
